version: "3"
services:
  python_scraper:
    build: 
      context: "."
      dockerfile: "Dockerfile"
    environment:
      - PYTHON_RUNNING_IN_CONTAINER=True
      - USE_REMOTE_WEBDRIVER=True
    networks: 
      - redbubble_scraper
    volumes:
      - scraped_images:/Scraped_Images
    depends_on:
      - selenium_remote_webdriver
  
  selenium_remote_webdriver:
    image: selenium/standalone-chrome:4.5.0-20220929
    shm_size: "2g"
    networks: 
      - redbubble_scraper


networks:
  redbubble_scraper: {}
volumes:
  scraped_images: